### ISSUE TITLE
LTS-7.12 and later do not pick up blaze-from-html version 0.8.13

### ISSUE THREAD

**Issue by mcmayer** [jaspervdj/blaze-html#108]
I'm assuming that `blaze-from-html` v0.8.13 is the version that features the `-t` option.

`blaze-from-html` version 0.8.13 is in LTS since [lts-7.12](https://www.stackage.org/lts-7.12), but when I build `blaze-from-html` using stack (e.g. `stack install blaze-from-html`) I get an executable that does not seem to have the `-t` option.

**Comment by mcmayer** [comment]
I just saw that the -t option is already implemented. I must have been picking up an older version.

**Comment by jaspervdj** [comment]
This might a confusion between `blaze-html` versions and `blaze-from-html` versions?  The latest `blaze-from-html` version is `0.3.2.1`.

**Comment by jaspervdj** [comment]
I've moved `blaze-from-html` to a separate repo (<https://github.com/jaspervdj/blaze-from-html>) and bumped the version to `0.4.0.0`.  It should work now.

**Comment by mcmayer** [comment]
perfect. Thank you!
