### ISSUE TITLE
Missing muted attribute

### ISSUE THREAD

**Issue by RamiroPastor** [jaspervdj/blaze-html#122]
https://www.w3schools.com/tags/att_audio_muted.asp

**Comment by JohnAZoidberg** [comment]
It's actually quite easy. Just add it to this list: https://github.com/jaspervdj/blaze-html/blob/41b2c42864627dfde2b757bb9a5db74d30862c4e/src/Util/GenerateHtmlCombinators.hs#L422

This is the list for HTML5, please also check for which other (X/)HTML versions this attribute is defined.
