### ISSUE TITLE
Hackage metadata revision to support bytestring 0.11

### ISSUE THREAD

**Issue by chris-martin** [jaspervdj/blaze-html#135]
Since bytestring-0.11 support seems to have only required bumping the bound, would you mind please making the revision to blaze-html-0.9.1.2 on Hackage? https://github.com/jaspervdj/blaze-html/pull/134/files

**Comment by Bodigrim** [comment]
@jaspervdj just a gentle reminder to revise `blaze-html` allowing `bytestring-0.11`.

**Comment by jaspervdj** [comment]
Done!  Sorry for the delay.

**Comment by chris-martin** [comment]
Thank you :smile:
