### ISSUE TITLE
onkeypress missing?

### ISSUE THREAD

**Issue by unhammer** [jaspervdj/blaze-html#139]
I can't find onkeypress in https://jaspervdj.be/blaze/docs/Text-Blaze-Html5-Attributes.html (and am getting a compilation error when trying via ihp-hsx)

If I read https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes correctly it should be possible on every html element, but maybe I'm misreading?

**Comment by jaspervdj** [comment]
Fixed in f874af6fcd9ad764acca038524f533841f250696
