### ISSUE TITLE
Version bounds for blaze-markup are (arguably) to wide

### ISSUE THREAD

**Issue by fhartwig** [jaspervdj/blaze-html#96]
Several modules in blaze-html re-export modules from blaze-markup. The current version of blaze-html depends on blaze-markup >= 0.6  && < 0.7. However, blaze-markup's interface changed between version 0.6.2 and 0.6.3 (`text` and `string` were added). This means that if someone does e.g.

    import qualified Text.Blaze.Htm5 as H
    foo = H.text "Hello"

, it may or or may not compile (using the same version of blaze-html!), depending on which version of blaze-markup is picked by cabal.
I think this means that any version of blaze-html should not depend on multiple versions of blaze-markup unless they have the exact same interface.

**Comment by jaspervdj** [comment]
Good point, thanks! Will fix.
