### ISSUE TITLE
Add back blaze-builder 0.3 support

### ISSUE THREAD

**Issue by snoyberg** [jaspervdj/blaze-html#97]
Currently, there are a number of packages which do not support blaze-builder 0.4:

- atto-lisp-0.2.2 (==0.3.*). No maintainer. @nominolo
- aws-0.11.2 (>=0.2.1.4 && < 0.4). FP Complete michael@fpcomplete.com @snoyberg. @aristidb
- blaze-builder-enumerator-0.2.0.6 (>=0.2.1.4 && < 0.4). No maintainer. @meiersi
- scotty-0.9.1 (>=0.3.3.0 && < 0.4). Andrew Farmer <afarmer@ittc.ku.edu>. @scotty-web
- snap-core-0.9.6.4 (>=0.2.1.4 && < 0.4). No maintainer. @mightybyte
- snap-server-0.9.4.6 (>=0.2.1.4 && < 0.4). No maintainer. @mightybyte

This leads to a situation where users of those packages are forced to use old versions of blaze-html and blaze-markup, which may not have all patches (for example, for QuickCheck 2.8 support). It's obviously preferable that these packages be updated with blaze-builder 0.4 support, but in the interim, would you consider relaxing the lower bound on blaze-builder in blaze-markup and blaze-html?

**Comment by jaspervdj** [comment]
I could consider it if it's really necessary, however, due to the changes in `blaze-builder`, the versions are definitely incompatible, the same code might result in slightly different HTML.

**Comment by snoyberg** [comment]
I think "slightly different HTML" wouldn't be a deal breaker, if it's semantically the same (which in all cases I've looked at, it has been).

**Comment by jaspervdj** [comment]
Fair enough, I want to be practical about this and relaxing the constraints a bit clearly the easiest and fastest way to help out the community.

**Comment by jaspervdj** [comment]
Uploaded `blaze-html-0.8.0.2` to Hackage which should fix the issue.

**Comment by snoyberg** [comment]
Thanks! However, `blaze-markup` still causes an issue here.

**Comment by jaspervdj** [comment]
Oh, good catch! I uploaded `blaze-markup-0.7.0.2` to Hackage as well now.

**Comment by snoyberg** [comment]
Perfect, thanks! Now I just have to bug the people who have upper bounds on blaze-html and blaze-markup...
